version: '3'
services:
  db:
    image: postgres
    ports:
    - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    command:
      - "postgres"
      - "-c"
      - "listen_addresses=*"

  adminer:
    image: adminer:4.8.1
    restart: always
    depends_on:
      - "db"
    ports:
    - "8000:8080"

  airflow:
    image: xddeng/airflow:airflow3_py3_11_localexecutor_postgres
    depends_on:
      - "db"
    restart: always
    volumes:
       - dag_folder:/usr/local/airflow/dags
    ports:
    - "8080:8080"
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgres://postgres:password@db:5432/postgres
      AIRFLOW__CORE__PARALLELISM: 4
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      AIRFLOW__WEBSERVER__PAGE_SIZE: 10
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "True"
    command: >
      sh -c "airflow standalone"

volumes:
  dag_folder:
